# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  exampleapp6:
    image: exampleapp6
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5234:5234
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
